[project]
name = "python-taxes"
version = "0.1.0"
description = "Development in progress - please come back later."
authors = [
    {name = "Stacy Noland", email = "46572585+stacynoland@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic (>=2.10.6,<3.0.0)"
]

[tool.poetry]
packages = [{include = "python_taxes", from = "src"}]


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
