[project]
name = "python-taxes"
version = "0.1.0"
description = "Development in progress - please come back later."
authors = [
    {name = "Stacy Noland", email = "46572585+stacynoland@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "pydantic (>=2.10.6,<3.0.0)"
]

[tool.poetry]
packages = [{include = "python_taxes", from = "src"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.1.0"
flake8 = "^7.2.0"
mypy = "^1.15.0"
tox = "^4.25.0"
black = "^25.1.0"
isort = "^6.0.1"

[tool.tox]
requires = ["tox>=4.25.0,<5.0.0"]
env_list = ["3.13", "3.12", "type", "lint", "format"]

[dependency-groups]
pytest = [
    "pytest>=8.3.0,<9.0.0",
]

[tool.tox.env_run_base]
description = "Run tests under {base_python}"
package = "wheel"
dependency_groups = ["pytest"]
deps = [
    "pytest-cov>=6.1.0,<7.0.0",
]
commands = [["pytest"]]

[tool.tox.env.type]
description = "Run type checking on code base"
package = "wheel"
dependency_groups = ["pytest"]
deps = [
    "mypy>=1.15.0,<2.0.0",
]
commands = [["mypy", "."]]

[tool.tox.env.lint]
description = "Run linters on code base"
package = "wheel"
deps = ["flake8>=7.2.0,<8.0.0"]
commands = [["flake8", "."]]

[tool.tox.env.format]
description = "Run formatters on code base"
package = "wheel"
deps = [
    "black>=25.1.0,<26.0.0",
    "isort>=6.0.0,<7.0.0",
]
commands = [
    ["black", "."],
    ["isort", "."],
]

[tool.isort]
profile = "black"
skip_gitignore = true
extend_skip = [".pytest_cache",]
skip_glob = ["*/__pycache__/*", "tests/__pycache__/*"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
