name: Checks

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/tests.yml
      - .github/workflows/checks.yml
      - .github/workflows/coverage.yml
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'src/**'
      - 'tests/**'
  workflow_call:

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install poetry
        uses: stacynoland/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-ansi
      - name: Run tox
        run: poetry run tox -e check