name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install poetry
      uses: stacynoland/install-poetry@v1
    - name: Install dependencies
      run: |
        poetry install --all-groups --no-interaction --no-ansi
    - name: Generate coverage report
      run: |
        poetry run pytest --cov --cov-report json
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: gh-pages-coverage-report
        path: coverage.json

  deploy:
    needs: coverage
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Download all workflow artifacts results
        uses: actions/download-artifact@v4
        with:
          path: gh-pages/
          pattern: gh-pages-*
          merge-multiple: true
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: 'gh-pages/'
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4