name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: [Checks]
    types: [completed]
  workflow_call:

jobs:
  coverage:
    uses: ./.github/workflows/coverage.yml
  deploy:
    needs: coverage
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Download all workflow artifacts results
        uses: actions/download-artifact@v4
        with:
          path: gh-pages/
          pattern: gh-pages-*
          merge-multiple: true
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: 'gh-pages/'
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4