# This workflow runs tests, coverage, and deploys to GitHub Pages
name: Run

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'src/**'
      - 'tests/**'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  coverage:
    needs: test
    uses: ./.github/workflows/coverage.yml
  deploy:
    needs: coverage
    uses: ./.github/workflows/deploy.yml