name: Tests

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'src/**'
      - 'tests/**'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: stacynoland/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-ansi
      - name: Run tests
        run: poetry run tox
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: gh-pages/coverage.json

  gh-pages:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: 'gh-pages/'
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4