name: Tests

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  test:

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
        poetry-version: ["latest", "2.1.1"]
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: stacynoland/install-poetry@v1
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          poetry install --with dev --no-interaction --no-ansi
      - name: Run tests
        run: poetry run tox -e py